name: CI build

# on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - 5.15.0
          
        platform:
          - gcc_64
          - msvc2019_64
          - mingw81

        include:
          - platform: gcc_64
            os: ubuntu-latest
            osname: linux
            arch: x86_64
            target: desktop

          - platform: msvc2019_64
            os: windows-latest
            osname: windows
            arch: win64_msvc2019_64
            target: desktop

          - platform: mingw81
            os: windows-latest
            osname: windows
            arch: win64_mingw81
            target: desktop
            
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
      - uses: actions/setup-python@v1
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{matrix.version}}
          host: ${{matrix.osname}}
      - name: qmake 
        run: |
          qmake QT_PLATFORM=${{matrix.platform}} "INSTALL_PATH=installer/bin" "QT_TOOL_PATH=${{steps.qt.outputs.qtdir}}/Tools" QtConfig.pro
          ${{steps.qt.outputs.make}} qmake_all
      - name: make app
        run: |
          ${{steps.qt.outputs.make}}
          ${{steps.qt.outputs.make}} install
          
      - name: Build installer
        run: |
            installer/init ${{steps.qt.outputs.qtdir}} ${{matrix.osname}} ${{matrix.arch}}
            
      - name: upload app to releases
        uses: Skycoder42/action-upload-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          directory: installer/output
          platform: ${{matrix.platform}}
          asset_name: qtconfig-${{matrix.osname}}-$${{matrix.arch}}
          tag: ${{github.ref}}
          overwrite: true

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          path: source
      - uses: actions/setup-python@v1
      - uses: Skycoder42/action-deploy-qt@master
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          version: 5.15.0
          host: ${{secrets.SSHFS_HOST}}
          key: ${{secrets.SSHFS_KEY}}
          port: ${{secrets.SSHFS_PORT}} 
